<h1>Edit Sample Data</h1>

<div class="row">
    <div class="span12">
        <?= $this->form()->openTag($form); ?>

        <?= $this->formRow($form->get('name')); ?>

        <?= $this->formRow($form->get('tag')); ?>

        <?= $this->formRow($form->get('revisionComment')); ?>

        <br>

        <?= $this->formInput(
                $form->get('save')->setAttributes(
                    array(
                        'value' => 'Update' ,
                        'class' => 'btn btn-warning'
                    )
                )
            ); ?>

        <a class="btn btn-danger delete" href="#">Delete</a>

        <?= $this->form()->closeTag($form); ?>
    </div>
</div>

<script>

$(function() {
    $('.delete').on('click', function(event) {
        if (!confirm('Are you sure?')) return;

        window.document.location = "<?= $this->url('edit' ,
                array(
                    'controller' => 'index' ,
                    'action' => 'delete' ,
                    'id' => $type->getId()
                )); ?>?revisionComment=" + encodeURIComponent($('[name="revisionComment"]').val());


    });
});

</script>

