<div class="row">
    <div class="span6">
        <h1>Sample Data </h1>
        <table class="table table-bordered table-hover table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Tag</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($records as $r): ?>
                    <tr>
                        <td><?= $r->getId(); ?></td>
                        <td><?= $r->getName(); ?></td>
                        <td><?= $r->getTag(); ?></td>
                        <td><a class="btn" href="<?= $this->url("edit", array("action" => "edit", "id" => $r->getId())) ?>">Edit</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="span6">
        <?php if (!$this->zfcUserIdentity()): ?>
            <!-- display the login form -->
            <?= $this->zfcUserLoginWidget(); ?>

            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <p>Sign in to add sample data</p>
            </div>

            <?php else: ?>
            <h1>Add Sample Data</h1>
            <!-- display the 'display name' of the user -->

            <?= $this->form()->openTag($form); ?>

            <?= $this->formRow($form->get('name')); ?>

            <?= $this->formRow($form->get('tag')); ?>

            <?= $this->formRow($form->get('revisionComment')); ?>

            <?= $this->formRow($form->get('save')); ?>

            <?= $this->form()->closeTag($form); ?>

        <?php endif ?>
    </div>
</div>
